In [ ]:
import kagglehub
path = kagglehub.dataset_download("akshaydattatraykhare/diabetes-dataset")

import os
os.listdir(path)

Using Colab cache for faster access to the 'diabetes-dataset' dataset.

['diabetes.csv']

In [ ]:
from kagglehub import KaggleDatasetAdapter

df = kagglehub.load_dataset(
    KaggleDatasetAdapter.PANDAS,
    "akshaydattatraykhare/diabetes-dataset",
    "diabetes.csv"
)

df.head()

/tmp/ipykernel_493/1762519444.py:3: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Using Colab cache for faster access to the 'diabetes-dataset' dataset.

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [ ]:
df.info()
df.isnull().sum()
df['Outcome'].value_counts()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

Outcome
0    500
1    268
Name: count, dtype: int64

In [ ]:
#แยก x และ y
X = df.drop("Outcome", axis=1)
y = df["Outcome"]

In [ ]:
import numpy as np

cols_with_zero = ["Glucose", "BloodPressure", "SkinThickness", "Insulin", "BMI"]

for col in cols_with_zero:
    df[col] = df[col].replace(0, np.nan)
    df[col] = df[col].fillna(df[col].median())

In [ ]:
from sklearn.model_selection import train_test_split

X = df.drop("Outcome", axis=1)
y = df["Outcome"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
#Normalize ข้อมูล
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential([
    Dense(16, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(8, activation='relu'),
    Dense(1, activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
history = model.fit(
    X_train, y_train,
    epochs=50,
    batch_size=16,
    validation_split=0.2
)

Epoch 1/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - accuracy: 0.6808 - loss: 0.6061 - val_accuracy: 0.6748 - val_loss: 0.5634
Epoch 2/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7415 - loss: 0.5365 - val_accuracy: 0.6911 - val_loss: 0.5340
Epoch 3/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7294 - loss: 0.5144 - val_accuracy: 0.7073 - val_loss: 0.5127
Epoch 4/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.7805 - loss: 0.4677 - val_accuracy: 0.7154 - val_loss: 0.4981
Epoch 5/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - accuracy: 0.7629 - loss: 0.4866 - val_accuracy: 0.7236 - val_loss: 0.4924
Epoch 6/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7538 - loss: 0.4959 - val_accuracy: 0.7398 - val_loss: 0.4818
Epoch 7/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7787 - loss: 0.4501 - val_accuracy: 0.7398 - val_loss: 0.4727
Epoch 8/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7955 - loss: 0.4644 - val_accuracy: 0.7561 - val_loss: 0.4689
Epoch 9/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7959 - loss: 0.4544 - val_accuracy: 0.7480 - val_loss: 0.4670
Epoch 10/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7917 - loss: 0.4473 - val_accuracy: 0.7480 - val_loss: 0.4623
Epoch 11/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7681 - loss: 0.4565 - val_accuracy: 0.7561 - val_loss: 0.4584
Epoch 12/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7828 - loss: 0.4448 - val_accuracy: 0.7561 - val_loss: 0.4557
Epoch 13/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7955 - loss: 0.4235 - val_accuracy: 0.7724 - val_loss: 0.4519
Epoch 14/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7958 - loss: 0.4445 - val_accuracy: 0.7642 - val_loss: 0.4533
Epoch 15/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7856 - loss: 0.4325 - val_accuracy: 0.7642 - val_loss: 0.4505
Epoch 16/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7654 - loss: 0.4499 - val_accuracy: 0.7642 - val_loss: 0.4471
Epoch 17/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7838 - loss: 0.4649 - val_accuracy: 0.7724 - val_loss: 0.4470
Epoch 18/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8153 - loss: 0.3945 - val_accuracy: 0.7724 - val_loss: 0.4451
Epoch 19/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7742 - loss: 0.4475 - val_accuracy: 0.7724 - val_loss: 0.4442
Epoch 20/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8162 - loss: 0.3817 - val_accuracy: 0.7724 - val_loss: 0.4436
Epoch 21/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8032 - loss: 0.4172 - val_accuracy: 0.7805 - val_loss: 0.4419
Epoch 22/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8078 - loss: 0.4170 - val_accuracy: 0.7724 - val_loss: 0.4428
Epoch 23/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8087 - loss: 0.3963 - val_accuracy: 0.7724 - val_loss: 0.4404
Epoch 24/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7855 - loss: 0.4162 - val_accuracy: 0.7805 - val_loss: 0.4400
Epoch 25/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8113 - loss: 0.4030 - val_accuracy: 0.7805 - val_loss: 0.4403
Epoch 26/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7916 - loss: 0.4164 - val_accuracy: 0.7724 - val_loss: 0.4392
Epoch 27/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8269 - loss: 0.3900 - val_accuracy: 0.7805 - val_loss: 0.4389
Epoch 28/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8398 - loss: 0.3709 - val_accuracy: 0.7805 - val_loss: 0.4396
Epoch 29/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8092 - loss: 0.3923 - val_accuracy: 0.7805 - val_loss: 0.4398
Epoch 30/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8178 - loss: 0.3874 - val_accuracy: 0.7805 - val_loss: 0.4382
Epoch 31/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8202 - loss: 0.4038 - val_accuracy: 0.7805 - val_loss: 0.4396
Epoch 32/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8049 - loss: 0.3890 - val_accuracy: 0.7805 - val_loss: 0.4394
Epoch 33/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8006 - loss: 0.4038 - val_accuracy: 0.7805 - val_loss: 0.4379
Epoch 34/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8113 - loss: 0.3766 - val_accuracy: 0.7724 - val_loss: 0.4390
Epoch 35/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7911 - loss: 0.4106 - val_accuracy: 0.7724 - val_loss: 0.4376
Epoch 36/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8005 - loss: 0.3957 - val_accuracy: 0.7642 - val_loss: 0.4379
Epoch 37/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7921 - loss: 0.4131 - val_accuracy: 0.7805 - val_loss: 0.4382
Epoch 38/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7968 - loss: 0.3965 - val_accuracy: 0.7724 - val_loss: 0.4363
Epoch 39/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8040 - loss: 0.3979 - val_accuracy: 0.7805 - val_loss: 0.4369
Epoch 40/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8325 - loss: 0.3663 - val_accuracy: 0.7805 - val_loss: 0.4372
Epoch 41/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7921 - loss: 0.4042 - val_accuracy: 0.7724 - val_loss: 0.4353
Epoch 42/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8192 - loss: 0.3730 - val_accuracy: 0.7805 - val_loss: 0.4367
Epoch 43/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8134 - loss: 0.3790 - val_accuracy: 0.7805 - val_loss: 0.4368
Epoch 44/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8220 - loss: 0.3795 - val_accuracy: 0.7724 - val_loss: 0.4360
Epoch 45/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8235 - loss: 0.3687 - val_accuracy: 0.7724 - val_loss: 0.4357
Epoch 46/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8378 - loss: 0.3540 - val_accuracy: 0.7805 - val_loss: 0.4375
Epoch 47/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8045 - loss: 0.3847 - val_accuracy: 0.7805 - val_loss: 0.4363
Epoch 48/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8121 - loss: 0.3748 - val_accuracy: 0.7805 - val_loss: 0.4364
Epoch 49/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8145 - loss: 0.3883 - val_accuracy: 0.7805 - val_loss: 0.4366
Epoch 50/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7763 - loss: 0.4213 - val_accuracy: 0.7805 - val_loss: 0.4354

In [ ]:
loss, acc = model.evaluate(X_test, y_test)
print("Neural Network Accuracy:", acc)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7363 - loss: 0.5520
Neural Network Accuracy: 0.7467532753944397

In [ ]:
model.save("diabetes_nn_model.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [ ]:
from google.colab import files
files.download("diabetes_nn_model.h5")