In [ ]:
import kagglehub

path = kagglehub.dataset_download("saurabhbadole/bank-customer-churn-prediction-dataset")
print(path)

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).
Downloading from https://www.kaggle.com/api/v1/datasets/download/saurabhbadole/bank-customer-churn-prediction-dataset?dataset_version_number=2...

100%|██████████| 262k/262k [00:00<00:00, 55.6MB/s]

Extracting files...
/root/.cache/kagglehub/datasets/saurabhbadole/bank-customer-churn-prediction-dataset/versions/2

In [ ]:
import os
os.listdir(path)

['Churn_Modelling.csv']

In [ ]:
import pandas as pd

file_path = path + "/Churn_Modelling.csv"
df = pd.read_csv(file_path)

df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
df.shape
df.info()
df.describe()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [ ]:
df.columns

Index(['CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary',
       'Exited'],
      dtype='object')

In [ ]:
df = pd.get_dummies(df, drop_first=True) #Encode categorical

In [ ]:
X = df.drop("Exited", axis=1) #แยก x และ y
y = df["Exited"]

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

rf = RandomForestClassifier()
rf.fit(X_train, y_train)

pred = rf.predict(X_test)
print("Accuracy:", accuracy_score(y_test, pred))

Accuracy: 0.8645

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

gb = GradientBoostingClassifier()
gb.fit(X_train, y_train)

pred_gb = gb.predict(X_test)
print("GB Accuracy:", accuracy_score(y_test, pred_gb))

GB Accuracy: 0.8675

In [ ]:
from xgboost import XGBClassifier

xgb = XGBClassifier(use_label_encoder=False, eval_metric="logloss")
xgb.fit(X_train, y_train)

pred_xgb = xgb.predict(X_test)
print("XGB Accuracy:", accuracy_score(y_test, pred_xgb))

XGB Accuracy: 0.8695

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [08:59:06] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

In [ ]:
from sklearn.metrics import accuracy_score

acc_rf = accuracy_score(y_test, pred)
acc_gb = accuracy_score(y_test, pred_gb)
acc_xgb = accuracy_score(y_test, pred_xgb)

print("Random Forest:", acc_rf)
print("Gradient Boosting:", acc_gb)
print("XGBoost:", acc_xgb)

Random Forest: 0.8645
Gradient Boosting: 0.8675
XGBoost: 0.8695

In [ ]:
scores = {
    "RandomForest": acc_rf,
    "GradientBoosting": acc_gb,
    "XGBoost": acc_xgb
}

best_model_name = max(scores, key=scores.get)
print("Best model:", best_model_name)

Best model: XGBoost

In [ ]:
import joblib

if best_model_name == "RandomForest":
    best_model = rf
elif best_model_name == "GradientBoosting":
    best_model = gb
else:
    best_model = xgb

joblib.dump(best_model, "best_churn_model.pkl")

['best_churn_model.pkl']

In [ ]:
from google.colab import files
files.download("best_churn_model.pkl")